### ISSUE TITLE
item show in and out animation，transition element not take effect

### ISSUE THREAD

**Issue by TornadoLess** [Akryum/vue-virtual-scroller#122] opened 2019-01-29 12:38 UTC
as the dom is reused，transformy -9999px ，the transitiongroup element wont take any effect or behaviour strangely. beg that add the item active and inacitive animation in future version

 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by Akryum** [comment] 2019-02-19 14:10
Duplicate of #11

**Closed by Akryum** 2019-02-19 14:10 UTC
Labels: enhancement
