### ISSUE TITLE
how to change 'z-index' any view in list ?

### ISSUE THREAD

**Issue by mohamadrezahedayati** [Akryum/vue-virtual-scroller#565] opened 2021-01-25 12:08 UTC
hello guys

I have list that each record is component and inside each 
component have drop down 

When the record is opened, it looks like this: 

![image](https://user-images.githubusercontent.com/43079809/105702714-6f40a880-5f21-11eb-8bb0-028b69f9534f.png)

The solution that came to my mind was that between the two lines, the top line should have more "z-index" than the bottom line , it looks like this: 

![image](https://user-images.githubusercontent.com/43079809/105703528-9f3c7b80-5f22-11eb-9c8b-9431532662bb.png)

![image](https://user-images.githubusercontent.com/43079809/105703640-ca26cf80-5f22-11eb-9137-d28e6c098da8.png)

My problem now is that I do not know how to implement this

@Akryum

**Comment by Akryum** [comment] 2021-02-11 17:05
Duplicate of #319

**Closed by Akryum** 2021-02-11 17:05 UTC

**Comment by w602542704** [comment] 2022-03-25 04:09
> hello guys
> 
> I have list that each record is component and inside each component have drop down
> 
> When the record is opened, it looks like this:
> 
> ![image](https://user-images.githubusercontent.com/43079809/105702714-6f40a880-5f21-11eb-8bb0-028b69f9534f.png)
> 
> The solution that came to my mind was that between the two lines, the top line should have more "z-index" than the bottom line , it looks like this:
> 
> ![image](https://user-images.githubusercontent.com/43079809/105703528-9f3c7b80-5f22-11eb-9c8b-9431532662bb.png)
> 
> ![image](https://user-images.githubusercontent.com/43079809/105703640-ca26cf80-5f22-11eb-9137-d28e6c098da8.png)
> 
> My problem now is that I do not know how to implement this
> 
> @Akryum
![image](https://user-images.githubusercontent.com/24689873/160052450-a4760e92-7158-4d7c-9daa-d5327065b64a.png)
****
我这样做完美解决
